accounts:
  - name: vuser
    coins: ["20000000000ubnt"]
  - name: minter
    coins: ["10000ubnt"]
validator:
  name: vuser
  staked: "100000000ubnt"
client:
  openapi:
    path: "docs/static/openapi.yml"
init:
  app:
    api:
      enable: true
    storage-dir: "~/.curium/storage"
    minimum-gas-prices: "0ubnt"
  client:
    output: "json"
    keyring-backend: "test"

  config:
    consensus:
      timeout_commit: "5s"
    p2p:
      addr_book_strict: false
    rpc:
      cors_allowed_origins:
        - "*"
genesis:
  app_state:
    tax:
      gasTaxBp: 100
      transferTaxBp: 1
      taxCollector: 'bluzelle1dvc2u4l84hyfeem5fmfm9eyjlndpsycwwfhtln'
    staking:
      params:
        bond_denom: "ubnt"
    crisis:
      constant_fee:
        denom: "ubnt"

    gov:
      deposit_params:
        min_deposit:
          - denom: "ubnt"
            amount: "1000000"
    mint:
      minter:
        inflation: "0.0"
      params:
        mint_denom: "ubnt"
        inflation_min: "0.0"
        inflation_max: "0.0"
        inflation_rate_change: "0.0"