accounts:
  - name: vuser
    coins: ["20000000000ubnt"]
  - name: minter
    coins: ["10000ubnt"]
validator:
  name: vuser
  staked: "100000000ubnt"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "../sdk/ts/src"
init:
  app:
    storage-dir: "~/.curium/storage"
    minimum-gas-prices: "0ubnt"
  client:
    output: "json"
    keyring-backend: "test"

  config:
    consensus:
      timeout_commit: "5s"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "ubnt"
    crisis:
      constant_fee:
        denom: "ubnt"

    gov:
      deposit_params:
        min_deposit:
          - denom: "ubnt"
            amount: "1000000"

    mint:
      params:
        mint_denom: "ubnt"

